# -*- coding: utf-8 -*-
"""SERNISSAN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cn2MKHTwl7-dE_Z0iGICwPKX90Y8mCLj
"""

#hola mundo
print("hola mundo")
#comentario